ARQUIOU  - ARQUIVO DE SAIDA RELATORIO                                   00010024
ARQ2101  - VALIDAR EMPRESTIMOS (ARQUIVO CLIENTES)                       00020024
ARQ2102  - LER CLIENTES E FAZER RELATORIO EM SAIDACLI                   00030024
ARQ2103  - LER CLIENTES E FAZER RELATORIO DE ACORDO COM SETOR           00040024
BASEARQ1 - BASE PARA LEITURA DE ARQUIVOS                                00050024
DATAEXE  - MODULO PARA DATA EM EXTENSO                                  00060024
DESAFIO  - DESAFIO DE LOGICA DOS RELOGIOS                               00070024
FR21CB01 - PRIMEIRO PROGRAMA                                            00080024
FR21CB02 - ACCEPT DE DADOS E PROCESSAMENTO                              00090024
FR21CB03 - ACCEPT DE DADOS EM UMA UNICA VARIAVEL                        00100024
FR21CB04 - REDEFINES DE DADOS                                           00110024
FR21CB05 - REDEFINES DE DADOS E ACCEPT EM STRING                        00120024
FR21CB06 - TREINO DE CALCULO (SOMA)                                     00130024
FR21CB07 - CALCULADORA SIMPLES                                          00140024
FR21CB08 - CALCULOS USANDO GIVVING E MASCARA                            00150024
FR21CB09 - TREINO DE CALCULO (COMPUTE)                                  00160024
FR21CB10 - EVALUATE (LOJA COM FRETE)                                    00170024
FR21CB11 - CALCULO DE MEDIA DOS ALUNOS                                  00180024
FR21CB12 - VARIAVEL BOLEANA                                             00190024
FR21CB13 - CALCULADORA DE JUROS                                         00200024
FR21CB14 - SOMAR TODOS OS DADOS DA SYSIN                                00210024
FR21CB15 - CALCULAR A TABUADA DE UM NUMERO                              00220024
FR21CB16 - CALCULO DE JUROS COMPOSTO                                    00230024
FR21DB01 - LER ARQUIVO DB2                                              00240024
FR21DB02 - LER DADOS DE ARQUIVO DB2 (CURSOR)                            00250024
FR21DB03 - INSERT EM TABELA DB2                                         00260024
FR21DB04 - DELETE DE TABELA DB2                                         00270024
